2022-11-02 17:10:34.956  2761-10400 pageboostd              pageboostd                           E  prefetch start : app comakreeexpensetracker
2022-11-02 17:10:34.956  2761-2761  pageboostd              pageboostd                           E  Received Reclaim command code 3, 121MB
2022-11-02 17:10:34.959   642-642   audit                   auditd                               E  type=1400 audit(1667398234.956:360): avc:  denied  { read } for  pid=2761 comm="pageboostd" name="product@overlay@NavigationBarMode3Button@NavigationBarMode3ButtonOverlay.apk@idmap" dev="sda32" ino=1800 scontext=u:r:pageboostd:s0 tcontext=u:object_r:resourcecache_data_file:s0 tclass=file permissive=0 SEPF_SM-N986B_11_0010 audit_filtered
2022-11-02 17:10:34.959   642-642   audit                   auditd                               E  type=1300 audit(1667398234.956:360): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=783bf75830 a2=0 a3=0 items=0 ppid=1 pid=2761 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="pageboostd" exe="/system/bin/pageboostd" subj=u:r:pageboostd:s0 key=(null)
2022-11-02 17:10:34.960   642-642   audit                   auditd                               E  type=1327 audit(1667398234.956:360): proctitle="/system/bin/pageboostd"
2022-11-02 17:10:34.960   642-642   audit                   auditd                               E  type=1400 audit(1667398234.956:361): avc:  denied  { search } for  pid=2761 comm="pageboostd" name="overlay" dev="dm-5" ino=78 scontext=u:r:pageboostd:s0 tcontext=u:object_r:vendor_overlay_file:s0 tclass=dir permissive=0 SEPF_SM-N986B_11_0010 audit_filtered
2022-11-02 17:10:34.960  2761-10400 pageboostd              pageboostd                           E  comakreeexpensetracker, amt 20324352 scnt 2 fcnt 7
2022-11-02 17:10:34.960  2761-10400 pageboostd              pageboostd                           E  prefetch end : app comakreeexpensetracker data_amount 20324352
2022-11-02 17:10:34.960  2761-10401 pageboostd              pageboostd                           E  prefetch start : app comviablefoodnetworkfileapp
2022-11-02 17:10:34.960  2761-10401 pageboostd              pageboostd                           E  comviablefoodnetworkfileapp, amt 0 scnt 2 fcnt 0
2022-11-02 17:10:34.960  2761-10401 pageboostd              pageboostd                           E  prefetch end : app comviablefoodnetworkfileapp data_amount 0
2022-11-02 17:10:34.960  2761-10402 pageboostd              pageboostd                           E  mem prepare start : 121 MB
2022-11-02 17:10:35.000  2761-10402 pageboostd              pageboostd                           E  mem prepare done : 126877696 bytes
2022-11-02 17:10:35.738   778-802   BufferQueueProducer     surfaceflinger                       E  [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_1813#0](id:30a00000062,api:0,p:-1,c:778) disconnect: not connected (req=1)
2022-11-02 17:10:35.937  7509-7509  AndroidRuntime          ru.myitschool.mte.test               E  FATAL EXCEPTION: main
                                                                                                    Process: ru.myitschool.mte.test, PID: 7509
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/~~oPbF51s-jP7dp1a-G5WcUQ==/ru.myitschool.mte.test-GvKBqMzJcHRuIaDl_T6hAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~oPbF51s-jP7dp1a-G5WcUQ==/ru.myitschool.mte.test-GvKBqMzJcHRuIaDl_T6hAA==/lib/arm64, /system/lib64]]
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8195)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7726)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7546)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/~~oPbF51s-jP7dp1a-G5WcUQ==/ru.myitschool.mte.test-GvKBqMzJcHRuIaDl_T6hAA==/base.apk"],nativeLibraryDirectories=[/data/app/~~oPbF51s-jP7dp1a-G5WcUQ==/ru.myitschool.mte.test-GvKBqMzJcHRuIaDl_T6hAA==/lib/arm64, /system/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8179)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7726) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7546) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2022-11-02 17:10:35.949  1116-1715  WindowManager           system_server                        E  win=Window{93940b5 u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5251 com.android.server.wm.ActivityRecord.notifyAppResumed:5272 com.android.server.wm.ActivityStack.resumeTopActivityInnerLocked:2386 com.android.server.wm.ActivityStack.resumeTopActivityUncheckedLocked:1873 com.android.server.wm.ActivityRecord.makeActiveIfNeeded:5510 com.android.server.wm.ActivityRecord.makeVisibleIfNeeded:5414 com.android.server.wm.EnsureActivitiesVisibleHelper.setActivityVisibilityState:187 
2022-11-02 17:10:35.955  1531-2661  TaskStackL...erAbstract com.android.systemui                 E  onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:587 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack> 
2022-11-02 17:10:35.972   700-782   HYPER-HAL               ven...amsung.hardware.hyper-service  E  [Request.cpp]acquire(): Request:: id : 649253, No Resource to set
2022-11-02 17:10:35.978  6244-7030  TaskStackL...erAbstract com...ng.android.service.aircommand  E  onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:587 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack> 
2022-11-02 17:10:35.998  2761-2761  pageboostd              pageboostd                           E  Received HALT command code 2
2022-11-02 17:10:36.347   663-728   Netd                    netd                                 E  getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2022-11-02 17:10:36.348  1116-1447  NetdEventL...nerService system_server                        E  DNS failed (10113) : 7
2022-11-02 17:10:36.399  2761-2761  pageboostd              pageboostd                           E  Received Reclaim command code 3, 121MB
2022-11-02 17:10:36.399  2761-10470 pageboostd              pageboostd                           E  prefetch start : app comviablefoodnetworkfileapp